### ISSUE TITLE
Panic when execute tk.Encode

### ISSUE THREAD

**Issue by qihuang0** [daulet/tokenizers#31]
Error msg:
thread '<unnamed>' panicked at src/lib.rs:86:54:
failed to cast tokenizer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10c94f736 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hcaf66bc4c0c453df
   1:        0x10c99685b - core::fmt::write::hc9c5f1836b413410
   2:        0x10c944752 - std::io::Write::write_fmt::h49df280499063c09
   3:        0x10c951fe8 - std::panicking::default_hook::{{closure}}::h52c0b2f44f6107c5
   4:        0x10c951c2e - std::panicking::default_hook::h5a6cf31501c161b2
   5:        0x10c952dc3 - std::panicking::rust_panic_with_hook::hda4640ee332466e9
   6:        0x10c952662 - std::panicking::begin_panic_handler::{{closure}}::haa3060694b34ea3d
   7:        0x10c94fc19 - std::sys::backtrace::__rust_end_short_backtrace::h8eb44913cfe71457
   8:        0x10c9522dc - _rust_begin_unwind
   9:        0x10c9c111c - core::panicking::panic_nounwind_fmt::hfed0a2f12e4318b1
  10:        0x10c9c11ca - core::panicking::panic_nounwind::h659854746b9fc37d
  11:        0x10c9c13e5 - core::panicking::panic_cannot_unwind::hd982c2e1ccbf0ef4
  12:        0x10c61c464 - _encode
  13:        0x10c5a521a - __cgo_8af6c9406da8_Cfunc_encode
thread caused non-unwinding panic. aborting.
SIGABRT: abort
PC=0x7ff805ad814a m=11 sigcode=0
signal arrived during cgo execution

**Comment by qihuang0** [comment]
This seems to be an occasional issue, and it doesn't occur in most cases.

**Comment by daulet** [comment]
@qihuang0 can you paste a code snippet to reproduce this? e.g. what was the input to cause the panic? Also what version of the library are you using.
